on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Abadi11/demo-action@v1.0.1
        with:
          name: 'Abadi'
      # Use the output from the `hello` step
      - name: Get the Output
        run: echo "The output ${{ steps.hello.outputs.greeting }}"