name: 'Multiple Events'

on:
  push:
    branches:
      -main
  pull-request:
    branches:
      -main
  release:
    types:
      - published
      - created

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"