name: Multiple Events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published, created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: | 
          echo "REF: $GITHUB_REF"
          echo "JOB_ID: $GITHUB_JOB"
          echo "ACTION: $GITHUB_ACTION"
          echo "ACTOR: $GITHUB_ACTOR"
