name: Workflow Commands

on: 
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Env Varaiable
        run: echo "NAME=abadi" >> $GITHUB_ENV

      - name: Set Output
        id: output_step
        run: echo "message=Hello" >> $GITHUB_OUTPUT

      - name: Debug Step
        run: echo "::debug::This is a debug step"

      - name: Grouping message
        run: | 
          echo "::group:: Welcoming Message"
          echo "This is"
          echo "${{steps.output_step.outputs.message}}" $NAME
          echo "::debug::This is a debug step"
          echo "Thanks for coming"
          echo "::endgroup::"

      - name: Add Mask
        run: echo "::add-mask::$NAME"